// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_CO2Panel = NULL;
lv_obj_t * ui_AirParticlePanel = NULL;
lv_obj_t * ui_AirQualityPanel = NULL;
lv_obj_t * ui_CO2Arc = NULL;
lv_obj_t * ui_CO2LowText = NULL;
lv_obj_t * ui_CO2HightText = NULL;
lv_obj_t * ui_CO2Value = NULL;
lv_obj_t * ui_PPMText = NULL;
lv_obj_t * ui_CO2LevelText = NULL;
lv_obj_t * ui_AirQualityMonitorText = NULL;
lv_obj_t * ui_TempValue = NULL;
lv_obj_t * ui_CelciusText = NULL;
lv_obj_t * ui_HumidityValue = NULL;
lv_obj_t * ui_PercentText = NULL;
lv_obj_t * ui_CO2Line = NULL;
lv_obj_t * ui_AirParticlesText = NULL;
lv_obj_t * ui_AirParticleLine1 = NULL;
lv_obj_t * ui_PPM1Text = NULL;
lv_obj_t * ui_PM1Value = NULL;
lv_obj_t * ui_ugm3TopText = NULL;
lv_obj_t * ui_AirParticleLine2 = NULL;
lv_obj_t * ui_PM25Text = NULL;
lv_obj_t * ui_PM25Value = NULL;
lv_obj_t * ui_ugm3MidText = NULL;
lv_obj_t * ui_AirParticleLine3 = NULL;
lv_obj_t * ui_PM10Text = NULL;
lv_obj_t * ui_PM10Value = NULL;
lv_obj_t * ui_ugm3BotText = NULL;
lv_obj_t * ui_NameText = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CO2Panel, 130);
    lv_obj_set_height(ui_CO2Panel, 170);
    lv_obj_set_x(ui_CO2Panel, -71);
    lv_obj_set_y(ui_CO2Panel, 20);
    lv_obj_set_align(ui_CO2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CO2Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CO2Panel, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CO2Panel, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CO2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirParticlePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AirParticlePanel, 132);
    lv_obj_set_height(ui_AirParticlePanel, 170);
    lv_obj_set_x(ui_AirParticlePanel, 71);
    lv_obj_set_y(ui_AirParticlePanel, 20);
    lv_obj_set_align(ui_AirParticlePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirParticlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AirParticlePanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AirParticlePanel, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirParticlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AirParticlePanel, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AirParticlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AirQualityPanel, 275);
    lv_obj_set_height(ui_AirQualityPanel, 33);
    lv_obj_set_x(ui_AirQualityPanel, 0);
    lv_obj_set_y(ui_AirQualityPanel, -90);
    lv_obj_set_align(ui_AirQualityPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirQualityPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AirQualityPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AirQualityPanel, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirQualityPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AirQualityPanel, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AirQualityPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_CO2Arc, 112);
    lv_obj_set_height(ui_CO2Arc, 112);
    lv_obj_set_x(ui_CO2Arc, -70);
    lv_obj_set_y(ui_CO2Arc, 23);
    lv_obj_set_align(ui_CO2Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_CO2Arc, 15, 35);
    lv_arc_set_value(ui_CO2Arc, 50);
    lv_arc_set_bg_angles(ui_CO2Arc, 115, 65);
    lv_obj_set_style_arc_color(ui_CO2Arc, lv_color_hex(0x072E05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CO2Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CO2Arc, lv_color_hex(0x0DFD5C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CO2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CO2Arc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CO2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CO2LowText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CO2LowText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2LowText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2LowText, -115);
    lv_obj_set_y(ui_CO2LowText, 73);
    lv_obj_set_align(ui_CO2LowText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2LowText, "400");
    lv_obj_set_style_text_color(ui_CO2LowText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2LowText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2LowText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2HightText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CO2HightText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2HightText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2HightText, -26);
    lv_obj_set_y(ui_CO2HightText, 74);
    lv_obj_set_align(ui_CO2HightText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2HightText, "5000");
    lv_obj_set_style_text_color(ui_CO2HightText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2HightText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2HightText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CO2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Value, -75);
    lv_obj_set_y(ui_CO2Value, 21);
    lv_obj_set_align(ui_CO2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Value, "----");
    lv_obj_set_style_text_color(ui_CO2Value, lv_color_hex(0x03DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPMText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPMText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPMText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPMText, -38);
    lv_obj_set_y(ui_PPMText, 30);
    lv_obj_set_align(ui_PPMText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPMText, "ppm");
    lv_obj_set_style_text_color(ui_PPMText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PPMText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPMText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2LevelText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CO2LevelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2LevelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2LevelText, -71);
    lv_obj_set_y(ui_CO2LevelText, -49);
    lv_obj_set_align(ui_CO2LevelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2LevelText, "CO2 Level");
    lv_obj_set_style_text_color(ui_CO2LevelText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2LevelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2LevelText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityMonitorText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AirQualityMonitorText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirQualityMonitorText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirQualityMonitorText, 4);
    lv_obj_set_y(ui_AirQualityMonitorText, -90);
    lv_obj_set_align(ui_AirQualityMonitorText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualityMonitorText, "Air Quality Monitor");
    lv_obj_set_style_text_color(ui_AirQualityMonitorText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AirQualityMonitorText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AirQualityMonitorText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValue, -117);
    lv_obj_set_y(ui_TempValue, 95);
    lv_obj_set_align(ui_TempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValue, "---");
    lv_obj_set_style_text_color(ui_TempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempValue, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CelciusText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CelciusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CelciusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CelciusText, -98);
    lv_obj_set_y(ui_CelciusText, 103);
    lv_obj_set_align(ui_CelciusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CelciusText, " °C\n");
    lv_obj_set_style_text_color(ui_CelciusText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CelciusText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CelciusText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumidityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityValue, -42);
    lv_obj_set_y(ui_HumidityValue, 95);
    lv_obj_set_align(ui_HumidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityValue, "---");
    lv_obj_set_style_text_color(ui_HumidityValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityValue, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PercentText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentText, -21);
    lv_obj_set_y(ui_PercentText, 94);
    lv_obj_set_align(ui_PercentText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentText, "%");
    lv_obj_set_style_text_color(ui_PercentText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PercentText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PercentText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Line = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CO2Line, 100);
    lv_obj_set_height(ui_CO2Line, 1);
    lv_obj_set_x(ui_CO2Line, -70);
    lv_obj_set_y(ui_CO2Line, 83);
    lv_obj_set_align(ui_CO2Line, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2Line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CO2Line, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirParticlesText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AirParticlesText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirParticlesText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirParticlesText, 69);
    lv_obj_set_y(ui_AirParticlesText, -50);
    lv_obj_set_align(ui_AirParticlesText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirParticlesText, "Air Particles");
    lv_obj_set_style_text_color(ui_AirParticlesText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AirParticlesText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AirParticlesText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirParticleLine1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AirParticleLine1, 100);
    lv_obj_set_height(ui_AirParticleLine1, 1);
    lv_obj_set_x(ui_AirParticleLine1, 70);
    lv_obj_set_y(ui_AirParticleLine1, -35);
    lv_obj_set_align(ui_AirParticleLine1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirParticleLine1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PPM1Text = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPM1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM1Text, 26);
    lv_obj_set_y(ui_PPM1Text, -24);
    lv_obj_set_align(ui_PPM1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM1Text, "PM1");
    lv_obj_set_style_text_color(ui_PPM1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PPM1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPM1Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM1Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PM1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM1Value, 66);
    lv_obj_set_y(ui_PM1Value, -8);
    lv_obj_set_align(ui_PM1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM1Value, "---");
    lv_obj_set_style_text_color(ui_PM1Value, lv_color_hex(0xFA4831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM1Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM1Value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ugm3TopText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ugm3TopText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ugm3TopText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ugm3TopText, 108);
    lv_obj_set_y(ui_ugm3TopText, 2);
    lv_obj_set_align(ui_ugm3TopText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ugm3TopText, "ug/m3");
    lv_obj_set_style_text_color(ui_ugm3TopText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ugm3TopText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ugm3TopText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirParticleLine2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AirParticleLine2, 100);
    lv_obj_set_height(ui_AirParticleLine2, 1);
    lv_obj_set_x(ui_AirParticleLine2, 70);
    lv_obj_set_y(ui_AirParticleLine2, 11);
    lv_obj_set_align(ui_AirParticleLine2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirParticleLine2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AirParticleLine2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirParticleLine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25Text = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PM25Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM25Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM25Text, 31);
    lv_obj_set_y(ui_PM25Text, 25);
    lv_obj_set_align(ui_PM25Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM25Text, "PM2.5");
    lv_obj_set_style_text_color(ui_PM25Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM25Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM25Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PM25Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM25Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM25Value, 66);
    lv_obj_set_y(ui_PM25Value, 40);
    lv_obj_set_align(ui_PM25Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM25Value, "---");
    lv_obj_set_style_text_color(ui_PM25Value, lv_color_hex(0xFA4831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM25Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM25Value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ugm3MidText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ugm3MidText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ugm3MidText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ugm3MidText, 108);
    lv_obj_set_y(ui_ugm3MidText, 47);
    lv_obj_set_align(ui_ugm3MidText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ugm3MidText, "ug/m3");
    lv_obj_set_style_text_color(ui_ugm3MidText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ugm3MidText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ugm3MidText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirParticleLine3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AirParticleLine3, 100);
    lv_obj_set_height(ui_AirParticleLine3, 1);
    lv_obj_set_x(ui_AirParticleLine3, 70);
    lv_obj_set_y(ui_AirParticleLine3, 56);
    lv_obj_set_align(ui_AirParticleLine3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirParticleLine3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PM10Text = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PM10Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM10Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM10Text, 30);
    lv_obj_set_y(ui_PM10Text, 69);
    lv_obj_set_align(ui_PM10Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM10Text, "PM10");
    lv_obj_set_style_text_color(ui_PM10Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM10Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM10Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM10Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PM10Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM10Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM10Value, 65);
    lv_obj_set_y(ui_PM10Value, 85);
    lv_obj_set_align(ui_PM10Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM10Value, "---");
    lv_obj_set_style_text_color(ui_PM10Value, lv_color_hex(0xFA4831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM10Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM10Value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ugm3BotText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ugm3BotText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ugm3BotText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ugm3BotText, 108);
    lv_obj_set_y(ui_ugm3BotText, 93);
    lv_obj_set_align(ui_ugm3BotText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ugm3BotText, "ug/m3");
    lv_obj_set_style_text_color(ui_ugm3BotText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ugm3BotText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ugm3BotText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NameText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameText, 105);
    lv_obj_set_y(ui_NameText, 110);
    lv_obj_set_align(ui_NameText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NameText, "@mikerankin");
    lv_obj_set_style_text_color(ui_NameText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_CO2Panel = NULL;
    ui_AirParticlePanel = NULL;
    ui_AirQualityPanel = NULL;
    ui_CO2Arc = NULL;
    ui_CO2LowText = NULL;
    ui_CO2HightText = NULL;
    ui_CO2Value = NULL;
    ui_PPMText = NULL;
    ui_CO2LevelText = NULL;
    ui_AirQualityMonitorText = NULL;
    ui_TempValue = NULL;
    ui_CelciusText = NULL;
    ui_HumidityValue = NULL;
    ui_PercentText = NULL;
    ui_CO2Line = NULL;
    ui_AirParticlesText = NULL;
    ui_AirParticleLine1 = NULL;
    ui_PPM1Text = NULL;
    ui_PM1Value = NULL;
    ui_ugm3TopText = NULL;
    ui_AirParticleLine2 = NULL;
    ui_PM25Text = NULL;
    ui_PM25Value = NULL;
    ui_ugm3MidText = NULL;
    ui_AirParticleLine3 = NULL;
    ui_PM10Text = NULL;
    ui_PM10Value = NULL;
    ui_ugm3BotText = NULL;
    ui_NameText = NULL;

}
