// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_CO2Panel;
extern lv_obj_t * ui_AirParticlePanel;
extern lv_obj_t * ui_AirQualityPanel;
extern lv_obj_t * ui_CO2Arc;
extern lv_obj_t * ui_CO2LowText;
extern lv_obj_t * ui_CO2HightText;
extern lv_obj_t * ui_CO2Value;
extern lv_obj_t * ui_PPMText;
extern lv_obj_t * ui_CO2LevelText;
extern lv_obj_t * ui_AirQualityMonitorText;
extern lv_obj_t * ui_TempValue;
extern lv_obj_t * ui_CelciusText;
extern lv_obj_t * ui_HumidityValue;
extern lv_obj_t * ui_PercentText;
extern lv_obj_t * ui_CO2Line;
extern lv_obj_t * ui_AirParticlesText;
extern lv_obj_t * ui_AirParticleLine1;
extern lv_obj_t * ui_PPM1Text;
extern lv_obj_t * ui_PM1Value;
extern lv_obj_t * ui_ugm3TopText;
extern lv_obj_t * ui_AirParticleLine2;
extern lv_obj_t * ui_PM25Text;
extern lv_obj_t * ui_PM25Value;
extern lv_obj_t * ui_ugm3MidText;
extern lv_obj_t * ui_AirParticleLine3;
extern lv_obj_t * ui_PM10Text;
extern lv_obj_t * ui_PM10Value;
extern lv_obj_t * ui_ugm3BotText;
extern lv_obj_t * ui_NameText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

